heat_template_version: 2014-10-16  
description: A simple server.  
    
resources:
  server:
    type: OS::Nova::Server
    properties:
      name: webServer
      flavor: m1.small     
      key_name: private
      image: CentOS
      networks:
        - port: { get_resource: port }
      user_data_format: RAW
      user_data: |
            #! /bin/sh -v
            sudo yum -y install httpd wordpress
            sudo systemctl enable httpd.service
            sudo emctl start httpd.service
            sudo setsebool -P httpd_can_network_connect_db=1

  port:
    type: OS::Neutron::Port
    properties:
      network: Server_network
      security_groups:
        - default

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: admin_floating_net

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: port }

