heat_template_version: 2014-10-16  
description: A simple server.  

parameters:
  port_web:
    type: number
    description: The port to reply to requests on
    default: 8080
    
resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: m1.small     
      key_name: private
      image: CentOS
      networks:
        - port: { get_resource: port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #! /bin/sh -v
            Body=$(hostname)
            Response="HTTP/1.1 200 OK\r\nContent-Length: ${#Body}\r\n\r\n$Body"
            while true ; do echo -e $Response | nc -llp %PORT%; done
          params:
            "%PORT%": {get_param: port_web}

  port:
    type: OS::Neutron::Port
    properties:
      network: stackServer_net
      security_groups:
        - default

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: admin_floating_net

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: port }

